In [76]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import seaborn as sns
%matplotlib inline

df = pd.read_csv('students_dropout.csv')

#  Tarea 1 y tarea 2
# nombre de las columnas
df.columns

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Displaced',
       'Educational special needs', 'Debtor', 'Tuition fees up to date',
       'Gender', 'Scholarship holder', 'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)

In [77]:
#tipo  de datos
df.dtypes

Marital status                                      int64
Application mode                                    int64
Application order                                   int64
Course                                              int64
Daytime/evening attendance                          int64
Previous qualification                              int64
Nacionality                                         int64
Mother's qualification                              int64
Father's qualification                              int64
Mother's occupation                                 int64
Father's occupation                                 int64
Displaced                                           int64
Educational special needs                           int64
Debtor                                              int64
Tuition fees up to date                             int64
Gender                                              int64
Scholarship holder                                  int64
Age at enrollm

In [78]:

#ver si hay datos nulos 
df.isnull().sum()

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular u

In [79]:
df.head()

Marital status  Application mode  Application order  Course   
0               1                 8                  5       2  \
1               1                 6                  1      11   
2               1                 1                  5       5   
3               1                 8                  2      15   
4               2                12                  1       3   

   Daytime/evening attendance  Previous qualification  Nacionality   
0                           1                       1            1  \
1                           1                       1            1   
2                           1                       1            1   
3                           1                       1            1   
4                           0                       1            1   

   Mother's qualification  Father's qualification  Mother's occupation  ...   
0                      13                      10                    6  ...  \
1                       1                       3                    4  ...   
2                      22                      27                   10  ...   
3                      23                      27                    6  ...   
4                      22                      28                   10  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)   
0                                    0                                    0  \
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    6   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)   
0                                       0  \
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)   
0                                    0                          0.000000  \
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate   
0                                               0               10.8  \
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 35 columns]

In [80]:
#verifique las inconsitencias y esta normal
df["Target"].unique()

array(['Dropout', 'Graduate', 'Enrolled'], dtype=object)

In [81]:
# se convierte en una variable categorica ya que en type, es la unica variable tipo object
df["Target"] = df["Target"].astype('category')

df["Target"] = df["Target"].cat.codes

#verificar si columna cambio
columna = df['Target']
columna.head(20)

0     0
1     2
2     0
3     2
4     2
5     2
6     2
7     0
8     2
9     0
10    2
11    2
12    0
13    2
14    2
15    0
16    1
17    2
18    2
19    1
Name: Target, dtype: int8

In [82]:
#filtro de  X con las variables independientes

X = df[['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification', 'Nacionality',
       "Mother's qualification", "Father's qualification",
       "Mother's occupation", "Father's occupation", 'Displaced',
       'Educational special needs', 'Debtor', 'Tuition fees up to date',
       'Gender', 'Scholarship holder', 'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP']]

X.head()

Marital status  Application mode  Application order  Course   
0               1                 8                  5       2  \
1               1                 6                  1      11   
2               1                 1                  5       5   
3               1                 8                  2      15   
4               2                12                  1       3   

   Daytime/evening attendance  Previous qualification  Nacionality   
0                           1                       1            1  \
1                           1                       1            1   
2                           1                       1            1   
3                           1                       1            1   
4                           0                       1            1   

   Mother's qualification  Father's qualification  Mother's occupation  ...   
0                      13                      10                    6  ...  \
1                       1                       3                    4  ...   
2                      22                      27                   10  ...   
3                      23                      27                    6  ...   
4                      22                      28                   10  ...   

   Curricular units 1st sem (without evaluations)   
0                                               0  \
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)   
0                                    0                                    0  \
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    6   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)   
0                                       0  \
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)   
0                                    0                          0.000000  \
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate   
0                                               0               10.8  \
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP  
0             1.4  1.74  
1            -0.3  0.79  
2             1.4  1.74  
3            -0.8 -3.12  
4            -0.3  0.79  

[5 rows x 34 columns]

In [83]:
#filtro de  Y con las variables dependientes
Y = df[['Target']]
Y

Target
0          0
1          2
2          0
3          2
4          2
...      ...
4419       2
4420       0
4421       0
4422       2
4423       2

[4424 rows x 1 columns]

In [84]:
#chequeo y balanceo

import seaborn as sns

print(Y.value_counts())

# es un balanceo desbalanceado entonces se debe hacer el metodo smote 

Target
2         2209
0         1421
1          794
Name: count, dtype: int64


In [85]:
#funcion para balancear
from imblearn.over_sampling import SMOTE

smote = SMOTE()
x_smote,y_smote = smote.fit_resample(X,Y)


In [86]:
import seaborn as sns

print(y_smote.value_counts())

Target
0         2209
1         2209
2         2209
Name: count, dtype: int64


In [87]:
#set de datos entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x_smote,y_smote,test_size=0.2)

In [88]:
#escalar variables ya que los datos escalan diferentes

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [89]:
#modelo de regresion logistica 
from sklearn.linear_model import LogisticRegression
regresion_log = LogisticRegression()
regresion_log.fit(X_train,y_train)

c:\Users\josea\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [90]:
#prediccion de datos de X_test
y_pred = regresion_log.predict(X_test)
y_pred

array([1, 1, 2, ..., 0, 1, 2], dtype=int8)

In [91]:
# matriz de confusion
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y_pred))


[[341  85  48]
 [ 40 318  65]
 [  6  53 370]]


verdadero positivo =[316,310,261]
falso negativo = [18,90,83,37]
falso positivo = [63,48]

In [92]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.72      0.79       474
           1       0.70      0.75      0.72       423
           2       0.77      0.86      0.81       429

    accuracy                           0.78      1326
   macro avg       0.78      0.78      0.78      1326
weighted avg       0.79      0.78      0.78      1326

